### ISSUE TITLE
[Bug] The program keeps opening the map, and close it, then open it, then close, ....

### ISSUE THREAD

**Issue by lampham7** [Night-stars-1/Auto_Star_Rail#10]
### Problem Description

after killing the mob here, the program keeps opening the map, and close it, then open again, then close, ....
![image](https://github.com/Night-stars-1/Auto_Star_Rail/assets/77009602/3ba5f7c0-ddfd-4d24-8edc-1ca8c89c51ab)
i tried to start the program at the next area, but it still keeps "open and close map" endlessly

### expected behavior

program keeps auto farming

### actual behavior

prgoram repeating open and close map

### Honkai-Star-Rail version

1.2

### Honkai Star Server

Global

### What equipment do you work on?

PC

### log

[日志文件.log](https://github.com/Night-stars-1/Auto_Star_Rail/files/12214228/default.log)

**Comment by Night-stars-1** [comment]
https://github.com/Night-stars-1/Auto_Star_Rail/releases/tag/v1.7.2
