### ISSUE TITLE
你好  卧按着做了出来的少了好多东西

### ISSUE THREAD

**Issue by xcdlh** [Night-stars-1/Auto_Star_Rail#11]
### 问题描述

你好  卧按着做了出来的少了好多东西

### 预期行为

少了很多功能选项

### 实际行为

只有几个选项

### 截图或录屏

![QQ截图20230731224537](https://github.com/Night-stars-1/Auto_Star_Rail/assets/118676805/c31e47c4-363e-4b55-a557-ff2b34b914a8)

### 自动锄大地脚本版本

v1.7.1

### 星穹铁道区服

国服

### 运行的客户端

PC

### 日志

[日志文件.log](https://github.com/Night-stars-1/Auto_Star_Rail/files/12216284/default.log)

**Comment by wendavid552** [comment]
+1 不过活动任务好像有点太麻烦了，一个就十几天，专门写一遍有点浪费，每日任务的话可以去看看StarrailCopilot？
