### ISSUE TITLE
[Bug] GUI has no option to run the program

### ISSUE THREAD

**Issue by lampham7** [Night-stars-1/Auto_Star_Rail#4]
### Problem Description

![image](https://github.com/Night-stars-1/Auto_Star_Rail/assets/77009602/467d9332-b02a-4d4b-8a2c-1bb77623d4c4)

### expected behavior

Should be able to run the program using GUI

### actual behavior

the "run the program" button disappeared

### Honkai-Star-Rail version

1.2

### Honkai Star Server

Global

### What equipment do you work on?

PC

### log

[日志文件.log](https://github.com/Night-stars-1/Auto_Star_Rail/files/12198862/default.log)

**Comment by Night-stars-1** [comment]
https://github.com/Night-stars-1/Auto_Star_Rail/releases/tag/v1.7.1
