### ISSUE TITLE
[Bug] Honkai_Star_Rail.py not working

### ISSUE THREAD

**Issue by lampham7** [Night-stars-1/Auto_Star_Rail#5]
### Problem Description

Honkai_Star_Rail.py not working
![image](https://github.com/Night-stars-1/Auto_Star_Rail/assets/77009602/1dba8f06-653e-4457-ba11-32fe38beaeef)

### expected behavior

Honkai_Star_Rail.py working

### actual behavior

Honkai_Star_Rail.py not working

### Honkai-Star-Rail version

1.2

### Honkai Star Server

Global

### What equipment do you work on?

PC

### log

[日志文件.log](https://github.com/Night-stars-1/Auto_Star_Rail/files/12198859/default.log)

**Comment by Night-stars-1** [comment]
https://github.com/Night-stars-1/Auto_Star_Rail/releases/tag/v1.7.1
